name: build-on-push
on:
  push:
    branches:
      - tools_renderpulses
  pull_request:
    branches:
      - tools_renderpulses

jobs:
  main:
    name: BuildOnPushPull 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run